[Application Options]
lnddir=/var/lib/lnd

[Bitcoin]
bitcoin.mainnet=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=127.0.0.1
bitcoind.rpcuser=lnd
bitcoind.rpcpass=RPC-PASSWORD-HERE
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

