server=1
txindex=1

datadir=/var/lib/bitcoin/
debuglogfile=/var/log/bitcoin/debug.log

dbcache=2048
maxconnections=40
maxuploadtarget=500

# Networking
listen=1

#Comment out Tor settings until it's installed.
#proxy=127.0.0.1:9050
#listenonion=1

rpcbind=127.0.0.1
rpcallowip=127.0.0.1

whitelist=download@127.0.0.1

rpcthreads=16
rpcworkqueue=256
#debug=net
#debug=rpc
#debug=validation
#debug=1
